### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by HostileGForce** [Duke-Jones/RegulatedNoise#34]
![temp](https://cloud.githubusercontent.com/assets/5627619/7551749/6297f5d0-f649-11e4-94db-e29e08a0f241.jpg)

ED installed on E:/
UAC disabled and restart.
Ran as Admin

LOG:
2015/05/09 12:47:51: ERROR: Error in main init function
2015/05/09 12:47:51: ERROR: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\progr'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at RegulatedNoise.Form1.SetProductPath() in k:\RegulatedNoise.git_DukeJones\RegulatedNoise\Form1.cs:line 642
   at RegulatedNoise.Form1..ctor() in k:\RegulatedNoise.git_DukeJones\RegulatedNoise\Form1.cs:line 155
2015/05/09 12:47:51: ERROR: Could not find a part of the path 'C:\progr'.
2015/05/09 12:47:51: ERROR:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at RegulatedNoise.Form1.SetProductPath() in k:\RegulatedNoise.git_DukeJones\RegulatedNoise\Form1.cs:line 642
   at RegulatedNoise.Form1..ctor() in k:\RegulatedNoise.git_DukeJones\RegulatedNoise\Form1.cs:line 155

**Comment by Duke-Jones** [comment]
try this:
https://forums.frontier.co.uk/showthread.php?t=137732&p=2127820&viewfull=1#post2127820

**Comment by HostileGForce** [comment]
it was originally installed on C and got the same result

**Comment by Duke-Jones** [comment]
have you created a new file and have put in your personal _correct_ paths ?

**Comment by HostileGForce** [comment]
correct path being? and what file?

**Comment by HostileGForce** [comment]
all the log tells me is that its looking for C:/progr
what if my ED is on a different drive like you suggest on the post?
either way, when it was installed on C, it still failed.

**Comment by Duke-Jones** [comment]
from the link above (please get the exact code from the link, at the moment i don't know how to insert xml code without errors) :

create a new file in the RegulatedNoise directory with the name "RegulatedNoiseSettings.xml"

put the following lines in it:
Code:

<?xml version="1.0"?>
<RegulatedNoiseSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <ProductsPath>F:\Games\ED\EDLaunch\Products</ProductsPath>
  <GamePath>F:\Games\ED\EDLaunch\Products\FORC-FDEV-D-1003</GamePath>
  <ProductAppData>C:\Users\Duke\AppData\Local\Frontier Developments\Elite Dangerous\Options</ProductAppData>
</RegulatedNoiseSettings>

<b>replace the given directories with your own directories.

**Comment by HostileGForce** [comment]
ok ill try that. might want to put that in some installation instructions for locating the install

**Comment by HostileGForce** [comment]
worked thank you
