### ISSUE TITLE
Cannot find log file

### ISSUE THREAD

**Issue by drphilth** [Duke-Jones/RegulatedNoise#38]
RegulatedNoise can't read my elite dangerous log file to find the current system info

It seems to be looking in C:\Users\Philip\AppData\Local\Frontier_Developments\Products\FORC-FDEV-D-1002\Logs

When it should be looking in D:\Elite\Products\FORC-FDEV-D-1002\Logs

Relevant line from filescanner log:

2015/05/11 16:54:41: Could not find a part of the path 'C:\Users\Philip\AppData\Local\Frontier_Developments\Products\FORC-FDEV-D-1002\Logs'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at RegulatedNoise.Form1.UpdateSystemNameFromLogFile_worker() in k:\RegulatedNoise.git_DukeJones\RegulatedNoise\Form1.cs:line 4272

![screenshot 2015-05-11 16 53 16](https://cloud.githubusercontent.com/assets/12397444/7569069/547010da-f7fe-11e4-9e0a-0c68b0cce2f3.png)

**Comment by drphilth** [comment]
Found the settings xml file. D'Oh
